# name: KATATONIA colors for Fish Themes
# url: https://fishshell.com/docs/current/interactive.html#syntax-highlighting
# upstream: ${upstream}
# author: Andrea Schiavini (original code by Casey Miller)

# preferred bg: 101010
# alt background: 200020

# Syntax Highlighting Colors
set -g fish_color_normal d0d0d0
set -g fish_color_command c080c0
set -g fish_color_keyword a060a0
set -g fish_color_quote 9a4f9a
set -g fish_color_redirection e0e0e0
set -g fish_color_end b070b0
set -g fish_color_error 804080
set -g fish_color_param d0d0d0
set -g fish_color_valid_path 6a2f6a
set -g fish_color_option 804080
set -g fish_color_comment 505050
set -g fish_color_selection --background=280028
set -g fish_color_operator b070b0
set -g fish_color_escape a060a0
set -g fish_color_autosuggestion 505050
set -g fish_color_cwd 9a4f9a
set -g fish_color_hostname e0e0e0
set -g fish_color_status 804080
set -g fish_color_cancel e0e0e0
set -g fish_color_search_match --background=280028

# Completion Pager Colors
set -g fish_pager_color_progress 804080
set -g fish_pager_color_prefix 6a2f6a
set -g fish_pager_color_completion d0d0d0
set -g fish_pager_color_description 505050
set -g fish_pager_color_selected_prefix 804080
set -g fish_pager_color_selected_completion 804080
set -g fish_pager_color_selected_background --background=280028
