# name: KATATONIA colors for Foot
# url: https://codeberg.org/dnkl/foot
# upstream: https://github.com/metalelf0/black-metal.nvim/raw/main/extras/foot/katatonia.ini
# author: Andrea Schiavini (original code by Casey Miller)

[colors-dark]
cursor=101010 d0d0d0
foreground=d0d0d0
background=101010
# alternate, darker background=200020
selection-foreground=d0d0d0
selection-background=300030
urls=e0e0e0

regular0=200020
regular1=804080
regular2=d0d0d0
regular3=c080c0
regular4=e0e0e0
regular5=a060a0
regular6=9a4f9a
regular7=d0d0d0

bright0=505050
bright1=804080
bright2=d0d0d0
bright3=c080c0
bright4=e0e0e0
bright5=6a2f6a
bright6=9a4f9a
bright7=d0d0d0

16=e0e0e0
17=804080
