# vim:ft=kitty

# name: KATATONIA colors for Kitty
# url: https://sw.kovidgoyal.net/kitty/conf.html
# upstream: ${upstream}
# author: Andrea Schiavini (original code by Casey Miller)

background #101010
# alternate, darker background #200020
foreground #d0d0d0
selection_background #300030
selection_foreground #d0d0d0
url_color #e0e0e0
cursor #d0d0d0
cursor_text_color #101010

# Tabs
active_tab_background #300030
active_tab_foreground #804080
inactive_tab_background #280028
inactive_tab_foreground #505050
#tab_bar_background #101010

# Windows
active_border_color #804080
inactive_border_color #505050

# normal
color0 #200020
color1 #804080
color2 #d0d0d0
color3 #c080c0
color4 #e0e0e0
color5 #a060a0
color6 #9a4f9a
color7 #d0d0d0

# bright
color8 #505050
color9 #804080
color10 #d0d0d0
color11 #c080c0
color12 #e0e0e0
color13 #6a2f6a
color14 #9a4f9a
color15 #d0d0d0

# extended colors
color16 #e0e0e0
color17 #804080
